import{initializeApp}from'https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js';
import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js';
import{getFirestore,doc,getDoc,setDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js';
const app=initializeApp({apiKey:'AIzaSyDUclkKHZC16QCYb5xeRHg55IZHmJA7_OI',authDomain:'lirik-lagu-8b4e2.firebaseapp.com',projectId:'lirik-lagu-8b4e2',storageBucket:'lirik-lagu-8b4e2.firebasestorage.app',messagingSenderId:'795702258465',appId:'1:795702258465:web:6d704efba58241c73eac60'});
const auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);
const moods={auto:'AUTO',soft:'SOFT',impact:'IMPACT',glitch:'GLITCH',pause:'PAUSE'};
const textCache=JSON.parse(localStorage.getItem('midnight-shelf-lyrics-v1')||'{}');
const sceneCache=JSON.parse(localStorage.getItem('midnight-shelf-scenes-v3')||'{}');
let song=null,user=null,draftScenes=[],playbackScenes=[],pos=0,bulkDirty=false,loadRequest=0;
let spotifyAPI=window.__spotifyIframeAPI||null,spotifyController=null,pendingTrackId=null,livePositionSeconds=0,lastAutoIndex=-1;
let tapWorking=[],tapCursor=0,tapHistory=[],tapTimerInterval=null;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),1900)}
function seed(n){const v=Math.sin(n*9283.71)*49297.13;return v-Math.floor(v)}
function parseTime(value){if(value==null||value==='')return null;if(typeof value==='number'&&Number.isFinite(value))return Math.max(0,value);const m=String(value).trim().replace(/^\[|\]$/g,'').match(/^(\d{1,2}):(\d{2}(?:\.\d{1,3})?)$/);return m?Math.max(0,Number(m[1])*60+Number(m[2])):null}
function formatTime(seconds,brackets=false){if(seconds==null||!Number.isFinite(Number(seconds)))return'';const s=Math.max(0,Number(seconds)),m=Math.floor(s/60),rest=(s-m*60).toFixed(2).padStart(5,'0'),value=`${String(m).padStart(2,'0')}:${rest}`;return brackets?`[${value}]`:value}
function parseLine(raw){const line=String(raw||'').trim(),match=line.match(/^\[(\d{1,2}):(\d{2}(?:\.\d{1,3})?)\]\s*(.*)$/);return match?{text:match[3].trim(),time:Number(match[1])*60+Number(match[2])}:{text:line,time:null}}
function scene(text='',mood='auto',time=null){return{text:String(text??''),mood:Object.hasOwn(moods,mood)?mood:'auto',time:parseTime(time)}}
function normalizeScenes(items){return Array.isArray(items)?items.map(item=>typeof item==='string'?(()=>{const p=parseLine(item);return scene(p.text,'auto',p.time)})():scene(item?.text,item?.mood,item?.time)):[]}
function scenesFromText(text){return String(text||'').split(/\n+/).map(parseLine).filter(x=>x.text).map(x=>scene(x.text,'auto',x.time))}
function cleanScenes(items=draftScenes){return normalizeScenes(items).map(x=>scene(x.text.trim(),x.mood,x.time)).filter(x=>x.text)}
function textFromScenes(items=draftScenes){return cleanScenes(items).map(x=>`${x.time==null?'':formatTime(x.time,true)+' '}${x.text}`).join('\n')}
function timedCount(items=draftScenes){return cleanScenes(items).filter(x=>x.time!=null).length}
function cacheDraft(){if(!song)return;const clean=cleanScenes();sceneCache[song.id]=clean;textCache[song.id]=textFromScenes(clean);localStorage.setItem('midnight-shelf-scenes-v3',JSON.stringify(sceneCache));localStorage.setItem('midnight-shelf-lyrics-v1',JSON.stringify(textCache))}
function syncBulkFromDraft(){$('#lyrics').value=textFromScenes(draftScenes);bulkDirty=false;$('#bulk-state').textContent=draftScenes.length?'synced':'ready'}
function updateSyncUI(){const count=timedCount(),badge=$('#sync-badge');badge.classList.toggle('show',count>0);badge.textContent=count?`${count} synced`:'synced';if(!count){$('#live-lyric').classList.remove('show');$('#live-lyric').textContent=''}}
function markDirty(){cacheDraft();updateSyncUI();$('#status').textContent='unsaved changes'}
function makeTool(icon,label,action,index,disabled=false){const b=document.createElement('button');b.type='button';b.className='scene-tool'+(action==='delete'?' delete':'');b.textContent=icon;b.title=label;b.disabled=disabled;b.addEventListener('click',()=>handleSceneTool(action,index));return b}
function renderSceneList(){const list=$('#scene-list'),editable=Boolean(user);list.replaceChildren();$('#editor').classList.toggle('readonly',!editable);['#lyrics','#import-scenes','#add-scene','#tap-sync','#save'].forEach(s=>$(s).disabled=!editable);$('#scene-count').textContent=`${cleanScenes().length} scene${cleanScenes().length===1?'':'s'}`;if(!draftScenes.length){const p=document.createElement('p');p.className='scene-empty';p.textContent=editable?'Tempel lirik lalu Split into scenes, atau tambah scene baru.':'Belum ada scene untuk lagu ini.';list.append(p);updateSyncUI();return}draftScenes.forEach((item,index)=>{const card=document.createElement('article');card.className='scene-card';const number=document.createElement('span');number.className='scene-number';number.textContent=String(index+1).padStart(2,'0');const input=document.createElement('textarea');input.className='scene-text';input.value=item.text;input.disabled=!editable;input.addEventListener('input',()=>{draftScenes[index].text=input.value;syncBulkFromDraft();markDirty();renderCountOnly()});const timing=document.createElement('label');timing.className='scene-time';timing.textContent='TIME';const timeInput=document.createElement('input');timeInput.placeholder='--:--';timeInput.value=formatTime(item.time);timeInput.disabled=!editable;timeInput.addEventListener('change',()=>{const raw=timeInput.value.trim(),parsed=parseTime(raw);if(raw&&parsed==null){toast('Format waktu: 00:12.50');timeInput.value=formatTime(draftScenes[index].time);return}draftScenes[index].time=parsed;timeInput.value=formatTime(parsed);syncBulkFromDraft();markDirty()});timing.append(timeInput);const mode=document.createElement('label');mode.className='scene-mode';mode.textContent='MOOD';const select=document.createElement('select');select.disabled=!editable;Object.entries(moods).forEach(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;o.selected=value===item.mood;select.append(o)});select.addEventListener('change',()=>{draftScenes[index].mood=select.value;markDirty()});mode.append(select);const tools=document.createElement('div');tools.className='scene-tools';tools.append(makeTool('↑','Move up','up',index,!editable||index===0),makeTool('↓','Move down','down',index,!editable||index===draftScenes.length-1),makeTool('◉','Preview','preview',index,false),makeTool('×','Delete','delete',index,!editable));card.append(number,input,timing,mode,tools);list.append(card)});updateSyncUI()}
function renderCountOnly(){$('#scene-count').textContent=`${cleanScenes().length} scene${cleanScenes().length===1?'':'s'}`}
function handleSceneTool(action,index){if(action==='preview'){const one=cleanScenes([draftScenes[index]]);return one.length?openCinema(one):toast('Isi scene dulu')}if(!user)return;if(action==='up'&&index>0)[draftScenes[index-1],draftScenes[index]]=[draftScenes[index],draftScenes[index-1]];if(action==='down'&&index<draftScenes.length-1)[draftScenes[index+1],draftScenes[index]]=[draftScenes[index],draftScenes[index+1]];if(action==='delete')draftScenes.splice(index,1);syncBulkFromDraft();markDirty();renderSceneList()}
function importBulk(show=true){const previous=draftScenes,parsed=scenesFromText($('#lyrics').value);draftScenes=parsed.map((x,i)=>scene(x.text,previous[i]?.mood||'auto',x.time));bulkDirty=false;syncBulkFromDraft();markDirty();renderSceneList();if(show)toast(`${draftScenes.length} scene siap diatur`)}
function editorScenes(){if(bulkDirty)importBulk(false);return cleanScenes()}
function updateAccess(){$('#auth').textContent=user?'SIGN OUT':'ADMIN SIGN IN';renderSceneList();if(song&&!user)$('#status').textContent='read only'}
function mountSpotify(){if(!song)return;pendingTrackId=song.id;if(spotifyController){spotifyController.loadUri(`spotify:track:${song.id}`);pendingTrackId=null;return}if(!spotifyAPI)return;spotifyAPI.createController($('#player'),{uri:`spotify:track:${song.id}`,width:'100%',height:'152'},controller=>{spotifyController=controller;controller.addListener('playback_update',event=>{const data=event?.data||{};if(typeof data.position==='number'){livePositionSeconds=data.position/1000;applyPlayback(livePositionSeconds)}});if(pendingTrackId)controller.loadUri(`spotify:track:${pendingTrackId}`);pendingTrackId=null})}
window.__onSpecialSpotifyIframeReady=api=>{spotifyAPI=api;mountSpotify()};if(window.__spotifyIframeAPI){spotifyAPI=window.__spotifyIframeAPI}
function bestTimedIndex(items,seconds){let index=-1,best=-Infinity;items.forEach((item,i)=>{if(item.time!=null&&item.time<=seconds&&item.time>=best){best=item.time;index=i}});return index}
function applyPlayback(seconds){const base=$('#cinema').classList.contains('open')?playbackScenes:cleanScenes(),index=bestTimedIndex(base,seconds);const live=$('#live-lyric');if(index<0){live.classList.remove('show');live.textContent='';return}live.textContent=base[index].text;live.classList.add('show');if($('#cinema').classList.contains('open')&&index!==lastAutoIndex){lastAutoIndex=index;pos=index;renderCinema()}}
async function choose(card){const request=++loadRequest;song=card.dataset;livePositionSeconds=0;lastAutoIndex=-1;$('#panel').classList.add('open');$('#world').textContent=card.querySelector('.tag').textContent;$('#title').textContent=song.name;$('#artist').textContent=song.artist;$('#status').textContent='loading';$('#live-lyric').classList.remove('show');mountSpotify();try{const snap=await getDoc(doc(db,'lyrics',song.id));if(request!==loadRequest)return;const saved=snap.exists()?snap.data():{},cloud=normalizeScenes(saved.scenes),local=normalizeScenes(sceneCache[song.id]),text=typeof saved.text==='string'?saved.text:(textCache[song.id]||'');draftScenes=cloud.length?cloud:(local.length?local:scenesFromText(text));syncBulkFromDraft();cacheDraft();$('#status').textContent=draftScenes.length?'cloud saved':'empty'}catch(error){if(request!==loadRequest)return;const local=normalizeScenes(sceneCache[song.id]);draftScenes=local.length?local:scenesFromText(textCache[song.id]||'');syncBulkFromDraft();$('#status').textContent='local only'}renderSceneList();$('#panel').scrollIntoView({behavior:'smooth',block:'center'})}
function reactionFor(text){const words=text?text.split(/\s+/).length:0;if(text.includes('!'))return'⚡';if(/\.{3,}/.test(text))return'···';if(words>0&&words<=4)return'✦';return'✹'}
function renderCinema(){const current=playbackScenes[pos]||scene('Tambahkan teks di editor untuk memulai.'),line=$('#line');line.className=`line mood-${current.mood||'auto'}`;line.textContent=current.text||'Tambahkan teks di editor untuk memulai.';void line.offsetWidth;line.classList.add('reveal');const reaction=$('#reaction');reaction.textContent=reactionFor(current.text);reaction.className='reaction';void reaction.offsetWidth;reaction.classList.add('show');$('#scene-progress').textContent=playbackScenes.length?`${String(pos+1).padStart(2,'0')} / ${String(playbackScenes.length).padStart(2,'0')} · ${moods[current.mood]||'AUTO'}`:'';$('#cinema-hint').textContent=timedCount(playbackScenes)?'mengikuti playback otomatis · tap / → untuk override':'tap layar / → untuk lanjut'}
function openCinema(scenes){if(!song)return toast('Pilih lagu dulu');playbackScenes=cleanScenes(scenes);if(!playbackScenes.length)return toast('Tambahkan minimal satu scene');pos=Math.max(0,bestTimedIndex(playbackScenes,livePositionSeconds));lastAutoIndex=-1;$('#cinema').className=`cinema open ${song.theme}`;$('#meta').textContent=`${song.name} · ${song.artist}`;renderCinema();if(timedCount(playbackScenes))applyPlayback(livePositionSeconds)}
function closeCinema(){$('#cinema').className='cinema';lastAutoIndex=-1}
function nextLine(direction){if(!playbackScenes.length)return;pos=(pos+direction+playbackScenes.length)%playbackScenes.length;lastAutoIndex=pos;renderCinema()}
function updateTapTimer(){const s=livePositionSeconds,m=Math.floor(s/60),rest=(s%60).toFixed(1).padStart(4,'0');$('#tap-timer').textContent=`${String(m).padStart(2,'0')}:${rest}`}
function renderTap(){const current=tapWorking[tapCursor];$('#tap-progress').textContent=`${Math.min(tapCursor,tapWorking.length)} / ${tapWorking.length} scenes`;$('#tap-current').textContent=current?.text||'🎉 semua scene sudah ditandai';$('#tap-next').textContent=tapWorking[tapCursor+1]?`berikutnya: ${tapWorking[tapCursor+1].text}`:'';$('#tap-button').disabled=!current;$('#tap-skip').disabled=!current;$('#tap-undo').disabled=!tapHistory.length;$('#tap-apply').disabled=!tapWorking.length}
function openTap(){if(!user)return toast('Login admin dulu');if(!song)return toast('Pilih lagu dulu');const scenes=editorScenes();if(!scenes.length)return toast('Tambahkan scene dulu');tapWorking=scenes.map(x=>scene(x.text,x.mood,x.time));tapCursor=0;tapHistory=[];$('#tap-track').textContent=`${song.name} · ${song.artist}`;renderTap();updateTapTimer();$('#tap-stage').classList.add('open');$('#tap-stage').setAttribute('aria-hidden','false');clearInterval(tapTimerInterval);tapTimerInterval=setInterval(updateTapTimer,100)}
function closeTap(){$('#tap-stage').classList.remove('open');$('#tap-stage').setAttribute('aria-hidden','true');clearInterval(tapTimerInterval)}
function tapNow(){if(tapCursor>=tapWorking.length)return;const index=tapCursor;tapHistory.push({type:'tap',index,previous:tapWorking[index].time});tapWorking[index].time=livePositionSeconds;tapCursor++;$('#tap-button').classList.remove('pulse');void $('#tap-button').offsetWidth;$('#tap-button').classList.add('pulse');renderTap()}
function skipTap(){if(tapCursor>=tapWorking.length)return;tapHistory.push({type:'skip',index:tapCursor});tapCursor++;renderTap()}
function undoTap(){const last=tapHistory.pop();if(!last)return;tapCursor=last.index;if(last.type==='tap')tapWorking[last.index].time=last.previous;renderTap()}
function applyTap(){if(!tapWorking.length)return;draftScenes=tapWorking.map(x=>scene(x.text,x.mood,x.time));syncBulkFromDraft();markDirty();renderSceneList();toast('Timing diterapkan — jangan lupa SAVE CLOUD');closeTap()}
function createDust(){const dust=$('#dust');for(let i=0;i<30;i++){const dot=document.createElement('i');dot.style.left=`${5+seed(i+3)*90}%`;dot.style.top=`${5+seed(i+31)*88}%`;dot.style.setProperty('--drift',`${((seed(i+55)*2-1)*48).toFixed(1)}px`);dot.style.setProperty('--dur',`${(3.5+seed(i+79)*5).toFixed(2)}s`);dot.style.animationDelay=`${(-seed(i+111)*8).toFixed(2)}s`;dust.append(dot)}}
document.querySelectorAll('.card').forEach(card=>card.addEventListener('click',()=>choose(card)));
$('#lyrics').addEventListener('input',()=>{bulkDirty=true;$('#bulk-state').textContent='ready to split';$('#status').textContent='unsaved changes'});$('#import-scenes').addEventListener('click',()=>importBulk(true));$('#add-scene').addEventListener('click',()=>{if(!user)return;draftScenes.push(scene());syncBulkFromDraft();markDirty();renderSceneList()});
onAuthStateChanged(auth,account=>{user=account;updateAccess()});$('#auth').addEventListener('click',async()=>{try{if(auth.currentUser)await signOut(auth);else await signInWithPopup(auth,provider)}catch(error){toast(error.code==='auth/unauthorized-domain'?'Tambahkan domain Vercel ke Firebase':'Login gagal')}});
$('#save').addEventListener('click',async()=>{if(!song)return toast('Pilih lagu dulu');if(!user)return $('#auth').click();const scenes=editorScenes(),text=textFromScenes(scenes);$('#status').textContent='saving';try{await setDoc(doc(db,'lyrics',song.id),{text,scenes,updatedAt:serverTimestamp()},{merge:true});draftScenes=scenes;syncBulkFromDraft();cacheDraft();$('#status').textContent='cloud saved';renderSceneList();toast('Scene + timing tersimpan ke cloud')}catch(error){$('#status').textContent='save denied';toast('Akun ini tidak punya izin simpan')}});
$('#open').addEventListener('click',()=>openCinema(editorScenes()));$('#close').addEventListener('click',closeCinema);$('#cinema').addEventListener('click',event=>{if(event.target.closest('#close'))return;nextLine(1)});$('#tap-sync').addEventListener('click',openTap);$('#tap-close').addEventListener('click',closeTap);$('#tap-cancel').addEventListener('click',closeTap);$('#tap-button').addEventListener('click',tapNow);$('#tap-skip').addEventListener('click',skipTap);$('#tap-undo').addEventListener('click',undoTap);$('#tap-apply').addEventListener('click',applyTap);
document.addEventListener('keydown',event=>{if($('#tap-stage').classList.contains('open')){if(event.key==='Escape')closeTap();if(event.key===' '){event.preventDefault();tapNow()}return}if(!$('#cinema').classList.contains('open'))return;if(event.key==='Escape')closeCinema();if(event.key==='ArrowRight'||event.key===' '){event.preventDefault();nextLine(1)}if(event.key==='ArrowLeft')nextLine(-1)});
createDust();updateAccess();